config/routes.rb
Rails.application.routes.draw do
  root 'fusens#index'

  devise_for :users

#  root_to: "home#index"
  resources :fusens
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "position/set_width", :concroller => :position
  get "position/set_position", :concroller => :position
  get "position/set_text", :concroller => :position

end

app/models/fusen.rb
class Fusen < ApplicationRecord
end

app/controllers/fusens_controller.rb
class FusensController < ApplicationController
  before_action :set_fusen, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /fusens
  # GET /fusens.json
  def index
    @fusens = Fusen.where(create_user: current_user.id)
    @fusen = Fusen.new
  end

  # GET /fusens/1
  # GET /fusens/1.json
  def show
   redirect_to action: 'index'
  end

  # GET /fusens/new
  def new
    @fusen = Fusen.new
  end

  # GET /fusens/1/edit
  def edit
    render layout: false
  end

  # POST /fusens
  # POST /fusens.json
  def create
    @fusen = Fusen.new(fusen_params)
    @fusen.dom_height = 120
    @fusen.dom_width = 240
    @fusen.create_user = current_user.id

    respond_to do |format|
      if @fusen.save
        format.html { redirect_to @fusen, notice: 'Fusen was successfully created.' }
        format.json { render :show, status: :created, location: @fusen }
      else
        format.html { render :new }
        format.json { render json: @fusen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fusens/1
  # PATCH/PUT /fusens/1.json
  def update
    respond_to do |format|
      if @fusen.update(fusen_params)
        format.html { redirect_to @fusen, notice: 'Fusen was successfully updated.' }
        format.json { render :show, status: :ok, location: @fusen }
      else
        format.html { render :edit }
        format.json { render json: @fusen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fusens/1
  # DELETE /fusens/1.json
  def destroy
    @fusen.destroy
    respond_to do |format|
      format.html { redirect_to fusens_url, notice: 'Fusen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fusen
      @fusen = Fusen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fusen_params
      params.require(:fusen).permit(:title, :message, :top, :left, :dom_height, :dom_width, :color)
    end
end

app/helpers/fusens_helper.rb
module FusensHelper
end

app/views/fusens/_form.html.erb
<%= form_with(model: fusen, local: true) do |form| %>
  <% if fusen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fusen.errors.count, "error") %> prohibited this fusen from being saved:</h2>

      <ul>
      <% fusen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :message, id: :fusen_message, :class => "form-control" %>
  </div>
  
  <div class="field">
    <select class="form-control" id="boxcolor" name="fusen[color]">
       <option value="boxblue">blue</option>
        <option value="boxyellow" selected="selected">yellow</option>
        <option value="boxred">red</option>
    </select> 
  </div>

  <div class="actions">
    <%= form.submit "create", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/fusens/_form_edit.html.erb
<%= form_with(model: fusen, local: true) do |form| %>
  <% if fusen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fusen.errors.count, "error") %> prohibited this fusen from being saved:</h2>

      <ul>
      <% fusen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :message, id: :edit_fusen_message, :class => "form-control" %>
  </div>
  
  <div class="field">
    <select class="form-control" id="boxcolor" name="fusen[color]">
      <% if fusen.color == "boxblue" %>
        <option value="boxblue" selected="selected">blue</option>
        <option value="boxyellow" >yellow</option>
        <option value="boxred">red</option>
      <% elsif fusen.color == "boxyellow" then %>
        <option value="boxblue">blue</option>
        <option value="boxyellow" selected="selected">yellow</option>
        <option value="boxred">red</option>
      <% elsif fusen.color == "boxred" then %>
        <option value="boxblue">blue</option>
        <option value="boxyellow" >yellow</option>
        <option value="boxred" selected="selected">red</option>
      <% else %>
        <option value="boxblue">blue</option>
        <option value="boxyellow" selected="selected">yellow</option>
        <option value="boxred">red</option>
      <% end %>
   </select> 
  </div>

  <div class="actions">
    <%= form.submit "create", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/fusens/edit.html.erb
      <div class="modal-header">
        <h3 class="modal-title" id="editModalLabel">Editing Fusen</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'form_edit', fusen: @fusen %>
      </div>
    </div>
 

app/views/fusens/index.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
      <span class="sr-only">メニュー</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
      <ul class="nav navbar-nav">
        <li>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
            New Fusen
          </button>
        </li>
        <li>
        </li>
      </ul>

  </div>
  
  <div id="gnavi" class="collapse navbar-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'パスワード変更', edit_user_registration_path, method: :get  %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete  %></li>
    </ul>
   </div>
</nav>

 <p id="notice"><%= notice %></p>

    <% @fusens.each do |fusen| %>
      <div class= "<%= fusen.id =%>"> 
        <div class="box <%= fusen.color =%> effect1"; 
             style="width: <%= fusen.dom_width =%>px; 
                    height: <%= fusen.dom_height =%>px; 
                    position: absolute; 
                    top: <%= fusen.top =%>px; 
                    left: <%= fusen.left =%>px;"> 
           <span style="float: right;">
              <%= link_to sanitize('<i class="glyphicon glyphicon-pencil"></i>'), edit_fusen_path(fusen), :data => {:toggle=>"modal", :target=>"#edit-Modal"} %>
              <%= link_to sanitize('<i class="glyphicon glyphicon-remove"></i>'), fusen, method: :delete %>
           </span>
             <%= auto_link(simple_format(fusen.message), :all, :target => "_blank") =%>
        </div> <!-- box effect1 -->
      </div> 
    <% end %>

<!-- new Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myModalLabel">New Fusen</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'form', fusen: @fusen %>
      </div>
    </div>
  </div>
</div>

<!-- edit Modal -->
<div class="modal fade" id="edit-Modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/fusens/new.html.erb
<h1>New Fusen</h1>

<%= render 'form', fusen: @fusen %>

<%= link_to 'Back', fusens_path %>

app/views/fusens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @fusen.title %>
</p>

<p>
  <strong>Message:</strong>
  <%= @fusen.message %>
</p>

<p>
  <strong>Top:</strong>
  <%= @fusen.top %>
</p>

<p>
  <strong>Left:</strong>
  <%= @fusen.left %>
</p>

<p>
  <strong>Dom height:</strong>
  <%= @fusen.dom_height %>
</p>

<p>
  <strong>Dom width:</strong>
  <%= @fusen.dom_width %>
</p>

<%= link_to 'Edit', edit_fusen_path(@fusen) %> |
<%= link_to 'Back', fusens_path %>